name: Publish GamingCanvas Package to npmjs

# Trigger the workflow when a release is published
on:
    release:
        types: [published]

jobs:
    build-and-publish:
        runs-on: ubuntu-latest

        steps:
            # Step 1: Check out the repository code
            - name: Checkout code
              uses: actions/checkout@v3

            # Step 2: Setup Node.js 24.x environment and set npm registry
            - name: Setup Node.js 24.x
              uses: actions/setup-node@v3
              with:
                  node-version: '24.x'
                  registry-url: 'https://registry.npmjs.org'

            # Step 3: Configure .npmrc to use npm token from secrets
            - name: Setup npm authentication
              run: echo "//registry.npmjs.org/:_authToken=\${{ secrets.NPM_TOKEN }}" > ~/.npmrc

            # Step 4: Install dependencies with yarn
            - name: Run install
              uses: borales/actions-yarn@v4
              with:
                  cmd: install # will run `yarn install` command

            # Step 5: Build the project
            - name: Build production bundle
              uses: borales/actions-yarn@v4
              with:
                  cmd: build # will run `yarn build` command

            # Step 6: Publish the package to npm
            - name: Publish to npm
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
